version = 0.1
[akeshpatil]
[akeshpatil.deploy]
[akeshpatil.deploy.parameters]
stack_name = "sam-app-user1-dev-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-120l2nak0j1aa"
s3_prefix = "sam-app-user1-dev-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
